#!/bin/bash

AGETTY_ARGS=${AGETTY_ARGS:-"--noclear"}

if [[ -z "${AGETTY_VTERMS}" ]];then
    AGETTY_VTERMS=${TTY_VTERMS:-7}
fi

agetty_provides() {
    echo tty
}

agetty_exists() {
    prog_exists agetty
}

agetty_start() {
    if [[ "${BEGINNING_RUNNER}" == rc.init ]];then
        for (( i=1; i<=${AGETTY_VTERMS}; i++ )); do
            sh -c "while true;do setsid agetty ${AGETTY_ARGS} tty${i} linux;done" &>/dev/null &
        done
    else
        false
    fi
}

agetty_reload() {
    agetty --reload
}

agetty_stop() {
    # stopping login terminals is almost always a bad idea.
    # don't allow it. if it's not desired then the user should be
    # smart enough to remove it from CORE_DAEMONS
    [[ "$BEGINNING_RUNNER" == rc.shutdown ]] || return 1
    kill $(pgrep agetty) >/dev/null 2>&1
}

agetty_status() {
    pgrep agetty >/dev/null 2>&1
}
