#!/bin/bash

CGMANAGER_ARGS=${CGMANAGER_ARGS:-}

cgmanager_exists() {
    prog_exists cgmanager
}

cgmanager_start() {
    cgmanager ${CGMANAGER_ARGS} >/dev/null 2>&1 &
    pidfile "$!" cgmanager
}

cgmanager_stop() {
    pidfilekill cgmanager
}

cgmanager_status() {
    pidfileexists cgmanager
}

