#!/bin/bash

CONNMAND_ARGS=${CONNMAND_ARGS:-}

connmand_exists() {
    prog_exists connmand
}

connmand_provides() {
    echo network
}

connmand_depends() {
    echo dbus dev
}

connmand_start() {
    connmand -n ${CONNMAND_ARGS} >/dev/null 2>&1 &
    pidfile "$!" connmand
}

connmand_stop() {
    pidfilekill connmand
}

connmand_status() {
    pidfileexists connmand
}
