#!/bin/bash

CRONIE_ARGS=${CRONIE_ARGS:-}

# vixie-cron uses `cron`, cronie is `crond`, busybox uses links
cronie_exists() {
    prog_exists crond && [[ "$(readlink -f $(type -fPp crond))" != */busybox ]]
}

cronie_provides() {
    echo cron
}

cronie_start() {
    crond -n ${CRONIE_ARGS} &
    pidfile "$!" cronie
}

cronie_stop() {
    pidfilekill cronie
}

cronie_status() {
    pidfileexists cronie
}

