#!/bin/bash

CUPS_BROWSED_ARGS=${CUPS_BROWSED_ARGS:-}

cups-browsed_exists() {
    prog_exists cups-browsed
}

cups-browsed_depends() {
    echo cupsd avahi-daemon
}

cups-browsed_start() {
    cups-browsed --autoshutdown=avahi ${CUPS_BROWSED_ARGS} >/dev/null 2>&1 &
    pidfile "$!" cups-browsed
}

cups-browsed_stop() {
    pidfilekill cups-browsed
}

cups-browsed_status() {
    pidfileexists cups-browsed
}
