#!/bin/bash

DBUS_ARGS=${DBUS_ARGS:-}

dbus_exists() {
    prog_exists dbus-daemon
}

dbus_start() {
    mkdir "@@runstatedir@@"/dbus >/dev/null 2>&1
    [[ -d "@@runstatedir@@"/dbus ]] || return 1
    dbus-uuidgen --ensure
    dbus-daemon --system --fork --nopidfile --print-pid ${DBUS_ARGS} > "@@runstatedir@@"/beginning/dbus.pid
}

dbus_reload() {
    pidfilekill -HUP dbus
}

dbus_stop() {
    pidfilekill dbus
}

dbus_status() {
    pidfileexists dbus
}
