#!/bin/bash

DHCPCD_ARGS=${DHCPCD_ARGS:-}
DHCPCD_CONF=${DHCPCD_CONF:-}
DHCPCD_IFACE=${DHCPCD_IFACE:-}

dhcpcd_exists() {
    prog_exists dhcpcd
}

dhcpcd_provides() {
    echo network
}

dhcpcd_start() {
    dhcpcd -q ${DHCPCD_CONF:+-f ${DHCPCD_CONF}} ${DHCPCD_ARGS} ${DHCPCD_IFACE} >/dev/null 2>&1 || return $?
}

dhcpcd_stop() {
    pidfilekill dhcpcd
}

dhcpcd_status() {
    pidfileexists dhcpcd
}
