#!/bin/bash

eudev_provides() {
    echo dev
}

eudev_exists() {
    if prog_exists udevd && ! prog_exists systemctl;then
        true
    else
        false
    fi
}

eudev_start() {
    udevd &
    local pid=$!
    udevadm trigger --action=add --type=subsystems
    udevadm trigger --action=add --type=devices
    status CUSTOM "eudev: devices settling"
    udevadm settle
    echo $pid > "@@runstatedir@@"/eudev.pid
}

eudev_reload() {
    status CUSTOM "eudev: reloading devices"
    udevadm control --reload
}

eudev_stop() {
    udevadm control --exit
}

eudev_status() {
    pidfileexists "@@runstatedir@@"/eudev.pid
}
