#!/bin/bash

HAVEGED_ARGS=${HAVEGED_ARGS:-}

haveged_exists() {
    prog_exists haveged
}

haveged_start() {
    haveged -p "@@runstatedir@@/haveged.pid" ${HAVEGED_ARGS}
}

haveged_stop() {
    pidfilekill haveged
}

haveged_status() {
    pidfileexists haveged
}

