#!/bin/bash

LIGHTTPD_ARGS=${LIGHTTPD_ARGS:-}
LIGHTTPD_CONF=${LIGHTTPD_CONF:-"@@sysconfdir@@"/lighttpd/lighttpd.conf}

lighttpd_exists() {
    prog_exists lighttpd
}

lighttpd_start() {
    lighttpd -t -f ${LIGHTTPD_CONF} ${LIGHTTPD_ARGS} >/dev/null 2>&1 || return $?
    lighttpd -D -f ${LIGHTTPD_CONF} ${LIGHTTPD_ARGS} >/dev/null 2>&1 &
    pidfile "$!" lighttpd
}

lighttpd_stop() {
    pidfilekill lighttpd
}

lighttpd_status() {
    pidfileexists lighttpd
}
