#!/bin/bash

OPENNTPD_ARGS=${OPENNTPD_ARGS:-}

openntpd_exists() {
    if prog_exists openntpd;then
        openntpd=openntpd
    elif prog_exists ntpctl;then
        openntpd=ntpd
    else
        return 1
    fi
}

openntpd_depends() {
    echo network
}

openntpd_start() {
    "${openntpd}" -p "@@runstatedir@@"/beginning/openntpd.pid ${OPENNTPD_ARGS} >/dev/null 2>&1
}

openntpd_stop() {
    pidfilekill openntpd
}

openntpd_status() {
    pidfileexists openntpd
}
