#!/bin/bash

OPENSSHD_ARGS=${OPENSSHD_ARGS:-}

opensshd_exists() {
    prog_exists sshd
}

opensshd_start() {
    if prog_exists sshd-keygen.sh;then
        # use sshd-keygen.sh if available; used by fedora and exherbo
        $(type -fPp sshd-keygen.sh >/dev/null 2>&1)
    elif prog_exists sshd-keygen;then
        # use sshd-keygen's built-in stuff otherwise
        sshd-keygen -A >/dev/null 2>&1
    fi
    setsid -w $(type -fPp sshd 2>/dev/null) ${OPENSSHD_ARGS} >/dev/null 2>&1
}

opensshd_reload() {
    pidfilekill -HUP sshd
}

opensshd_stop() {
    setsid -w kill $(<"@@runstatedir@@"/sshd.pid)
}

opensshd_status() {
    pidfileexists "@@runstatedir@@"/sshd.pid
}
