#!/bin/bash

OPENNTPD_ARGS=${OPENNTPD_ARGS:-}

openntpd_exists() {
    prog_exists openntpd
}

openntpd_depends() {
    echo network
}

openntpd_start() {
    openntpd -p "@@runstatedir@@"/beginning/openntpd.pid ${OPENNTPD_ARGS} >/dev/null 2>&1
}

openntpd_stop() {
    pidfilekill openntpd
}

openntpd_status() {
    pidfileexists openntpd
}
