#!/bin/bash

UPOWER_ARGS=${UPOWER_ARGS:-}

PATH="@@libexecdir@@:${PATH}"

upower_exists() {
    prog_exists upowerd
}

upower_depends() {
    echo dbus
}

upower_start() {
    upowerd ${UPOWER_ARGS} >/dev/null 2>&1 &
    pidfilewrite $! upower
}

upower_stop() {
    pidfilekill upower
}

upower_status() {
    pidfileexists upower
}

