#!/bin/bash

VIXIE_CRON_ARGS=${VIXIE_CRON_ARGS:-}

# vixie-cron uses `cron`, cronie is `crond`, busybox uses links
vixie-cron_exists() {
    prog_exists cron
}

vixie-cron_provides() {
    echo cron
}

vixie-cron_start() {
    cron -n ${VIXIE_CRON_ARGS} &
    pidfile "$!" vixie-cron
}

vixie-cron_stop() {
    pidfilekill vixie-cron
}

vixie-cron_status() {
    pidfileexists vixie-cron
}

