#!/bin/bash

WICD_ARGS=${WICD_ARGS:-}

wicd_exists() {
    prog_exists wicd
}

wicd_provides() {
    echo network
}

wicd_depends() {
    echo dbus dev
}

wicd_start() {
    wicd --no-daemon ${WICD_ARGS} >/dev/null 2>&1 &
    pidfile "$!" wicd
}

wicd_stop() {
    pidfilekill wicd
}

wicd_status() {
    pidfileexists wicd
}
