#!/bin/bash

ZNC_ARGS=${ZNC_ARGS:-}
ZNC_USER=${ZNC_USER:-"znc"}

znc_exists() {
    prog_exists znc
}

znc_start() {
    if [[ "${ZNC_USER}" ]];then
        touch "@@runstatedir@@"/beginning/znc.pid && chown "${ZNC_USER}" "@@runstatedir@@"/beginning/znc.pid
        su -s $(type -fPp sh) -c "znc -f ${ZNC_ARGS}" "${ZNC_USER}" >/dev/null 2>&1 &
    else
        znc -f ${ZNC_ARGS} >/dev/null 2>&1 &
    fi
    pidfile "$!" znc
}

znc_stop() {
    pidfilekill znc
}

znc_status() {
    pidfileexists znc
}
